name: StarHub EPG Auto Update

on:
  schedule:
    - cron: '0 18 * * *'   # 比 Hami 早10分钟
  workflow_dispatch:
  push:
    paths:
      - 'starhub/**'

jobs:
  update-starhub:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install deps
      run: |
        pip install requests
        pip install xmltodict

    - name: Run StarHub EPG
      run: |
        echo "🚀 Running StarHub EPG..."
        cd starhub
        python starhub_epg.py

    - name: Commit StarHub result
      run: |
        git config user.name "github-actions"
        git config user.email "bot@github.com"

        git add starhub/

        if git diff --cached --quiet; then
          echo "⚠️ No changes"
        else
          git commit -m "📺 StarHub EPG update $(date -u '+%Y-%m-%d %H:%M:%S')"
          git push
        fi
